### ISSUE TITLE
Images not being copied recursively when generating the site statically.

### ISSUE THREAD

**Issue by MrJoy** [envygeeks/jekyll-assets#15]
So, using the `config.ru` inclusion to serve assets dynamically, requests for say, `/assets/some_dir/foo.png` work fine.  However, when generating the site statically, only images from `source/_assets/images` are copied -- not `source/_assets/images/some_dir`.

The relevant portion of my config.ru:

``` ruby
$root = ::File.dirname(__FILE__)
require File.expand_path(File.join($root, 'plugins/assets'))
map "/assets" do
  environment = Sprockets::Environment.new
  environment.append_path "source/_assets/stylesheets"
  environment.append_path "source/_assets/javascripts"
  environment.append_path "source/_assets/images"
  environment.append_path "source/_assets/fonts"
  run environment
end
```

And the relevant portion of my assets.yml (compiled by Octopress into _config.yml):

``` yaml

---
assets:
  #
  # Pathname of the destination of generated (bundled) assets relative
  # to the destination of the root.
  #
  dirname: assets
  #
  # Base URL of assets paths.
  #
  baseurl: /assets/
  #
  # Pathnames where to find assets relative to the root of the site.
  #
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
    - _assets/fonts
  #
  # Compression/minification tools.
  #
  compress:
    js:   uglifier
    css:  sass
  #
  # CDN URL.
  #
#  baseurl: //my.super-cool-cdn.com/
  #
  # Cache-busting.
  # Options are:
  # none - no cachebuster added to URL.
  # soft - filename is left alone, but ?cb=<x> is added via asset path helpers.
  # hard - filename is modified with checksum.
  #
  cachebust: none
```
