### ISSUE TITLE
Ignore asset url query string or anchor when generating path

### ISSUE THREAD

**Issue by createdbypete** [envygeeks/jekyll-assets#20]
I encountered and error when trying to use [Font Awesome](https://github.com/FortAwesome/Font-Awesome), this is however a more general bug I believe relating to the `asset_path` method.

The following is the code I used, edited to take advantage of `font-path()`. This code fails because it is looking for a filename that includes the query string. Removing everything after the `?` will not throw any errors.

``` scss
@font-face {
  font-family: 'FontAwesome';
  src: url(font-path('fontawesome-webfont.eot?v=3.0.1'));
  src: url(font-path('fontawesome-webfont.eot?#iefix&v=3.0.1')) format("embedded-opentype"),
       url(font-path('fontawesome-webfont.woff?v=3.0.1')) format("woff"),
       url(font-path('fontawesome-webfont.ttf?v=3.0.1')) format("truetype");
  font-weight: normal;
  font-style: normal;
}
```

This is not a problem only for this plugin, I found [this issue](https://github.com/rails/rails/pull/7956) in the Rails repo that proposes a simple solution.

---

If there is a work around other than this update that I'm missing please let me know!
