### ISSUE TITLE
SHA256 Intgerity Tag Issues with Firefox?

### ISSUE THREAD

**Issue by ckreon** [envygeeks/jekyll-assets#270]
I'm having a strange issue in Firefox where my assets are failing the integrity check.

The console error from Firefox:

> None of the "sha256" hashes in the integrity attribute match the content of the subresource.

My asset _config options:

```
# Asset Settings
assets:
  cache: false
  sources:
    - _assets/pdf
    - _assets/icons
```

This happens both on the production server and in a localhost environment. The site works fine in other browsers (Safari, Chrome). Is Firefox the only browser actually enforcing the integrity check? I'm not sure why it would fail to begin with though.

I link to my assets using the given tags:
- {% css main %} and {% asset_path %} in HTML files
- font_path() and image_path() in scss files

Any ideas on how I could trace down the issue here?
