### ISSUE TITLE
Tags and filters in assets seem not to be parsed by liquid

### ISSUE THREAD

**Issue by hv15** [envygeeks/jekyll-assets#29]
I one of my assets (main.css) I use jekyll-asset tags to link to other assets (in this case font files). Neither the tag nor its filter counterpart are parsed by liquid.

The section of css in question is:

``` css
@font-face {
    font-family: 'Lacuna';
    src: url('{% asset_path font/lacuna-webfont.eot %}');
    src: url('{% asset_path font/lacuna-webfont.eot %}?#iefix') format('embedded-opentype'),
         url('{% asset_path font/lacuna-webfont.woff %}') format('woff'),
         url('{% asset_path font/lacuna-webfont.ttf %}') format('truetype'),
         url('{% asset_path font/lacuna-webfont.svg %}#LacunaRegular') format('svg');
    font-weight: normal;
    font-style: normal;
}
```

which after a build looks like this:

``` css
@font-face {
     font-family:'Lacuna';
     src:url("{% asset_path font/lacuna-webfont.eot %}");
     src:url("{% asset_path font/lacuna-webfont.eot %}?#iefix") format("embedded-opentype"),
          url("{% asset_path font/lacuna-webfont.woff %}") format("woff"),
          url("{% asset_path font/lacuna-webfont.ttf %}") format("truetype"),
          url("{% asset_path font/lacuna-webfont.svg %}#LacunaRegular") format("svg");
   font-weight:normal;
   font-style:normal;
}
```

Furthermore, if I switch to using the filter instead, jekyll errors out and never completes the build.

This

``` css
@font-face {
    font-family: 'Lacuna';
    src: url('{{ 'font/lacuna-webfont.eot' | asset_path }}');
    src: url('{% asset_path font/lacuna-webfont.eot %}?#iefix') format('embedded-opentype'),
         url('{% asset_path font/lacuna-webfont.woff %}') format('woff'),
         url('{% asset_path font/lacuna-webfont.ttf %}') format('truetype'),
         url('{% asset_path font/lacuna-webfont.svg %}#LacunaRegular') format('svg');
    font-weight: normal;
    font-style: normal;
}
```

causes this: 

```
 $ jekyll build
Configuration file: /cygdrive/c/Users/Hans/git/hans.viessmann.co/_config.yml
            Source: .
       Destination: ./_site
      Generating...   Liquid Exception: Invalid CSS after ".../lacuna-webfont": expected ")", was ".eot' | asset_p..." (in /cygdrive/c/Users/Hans/git/hans.viessmann.co/_assets/stylesheets/main.css) in default
(sass):8
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/scss/parser.rb:1148:in `expected'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/script/lexer.rb:199:in `expected!'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/script/parser.rb:476:in `assert_tok'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/script/parser.rb:332:in `funcall'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/script/parser.rb:319:in `ident'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/script/parser.rb:228:in `unary_not'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/script/parser.rb:228:in `unary_div'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/script/parser.rb:228:in `unary_minus'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/script/parser.rb:228:in `unary_plus'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/script/parser.rb:209:in `times_div_or_mod'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/script/parser.rb:209:in `plus_or_minus'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/script/parser.rb:209:in `relational'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/script/parser.rb:209:in `eq_or_neq'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/script/parser.rb:209:in `and_expr'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/script/parser.rb:209:in `or_expr'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/script/parser.rb:298:in `space'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/script/parser.rb:283:in `interpolation'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/script/parser.rb:246:in `expr'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/script/parser.rb:470:in `assert_expr'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/script/parser.rb:49:in `parse'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/scss/parser.rb:1022:in `sass_script'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/scss/parser.rb:882:in `value!'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/scss/parser.rb:859:in `declaration'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/scss/parser.rb:582:in `block in declaration_or_ruleset'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/scss/parser.rb:1122:in `call'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/scss/parser.rb:1122:in `rethrow'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/scss/parser.rb:592:in `declaration_or_ruleset'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/scss/parser.rb:554:in `block_child'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/scss/parser.rb:546:in `block_contents'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/scss/parser.rb:166:in `directive_body'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/scss/parser.rb:158:in `directive'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/scss/parser.rb:553:in `block_child'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/scss/parser.rb:543:in `block_contents'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/scss/parser.rb:82:in `stylesheet'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/scss/parser.rb:27:in `parse'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/engine.rb:342:in `_to_tree'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/engine.rb:315:in `_render'
/usr/lib/ruby/gems/1.9.1/gems/sass-3.2.9/lib/sass/engine.rb:262:in `render'
/usr/lib/ruby/gems/1.9.1/gems/sprockets-2.9.3/lib/sprockets/sass_compressor.rb:19:in `evaluate'
/usr/lib/ruby/gems/1.9.1/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/usr/lib/ruby/gems/1.9.1/gems/sprockets-2.9.3/lib/sprockets/context.rb:197:in `block in evaluate'
/usr/lib/ruby/gems/1.9.1/gems/sprockets-2.9.3/lib/sprockets/context.rb:194:in `each'
/usr/lib/ruby/gems/1.9.1/gems/sprockets-2.9.3/lib/sprockets/context.rb:194:in `evaluate'
/usr/lib/ruby/gems/1.9.1/gems/sprockets-2.9.3/lib/sprockets/bundled_asset.rb:25:in `initialize'
/usr/lib/ruby/gems/1.9.1/gems/sprockets-2.9.3/lib/sprockets/base.rb:377:in `new'
/usr/lib/ruby/gems/1.9.1/gems/sprockets-2.9.3/lib/sprockets/base.rb:377:in `build_asset'
/usr/lib/ruby/gems/1.9.1/gems/sprockets-2.9.3/lib/sprockets/index.rb:94:in `block in build_asset'
/usr/lib/ruby/gems/1.9.1/gems/sprockets-2.9.3/lib/sprockets/caching.rb:51:in `cache_asset'
/usr/lib/ruby/gems/1.9.1/gems/sprockets-2.9.3/lib/sprockets/index.rb:93:in `build_asset'
/usr/lib/ruby/gems/1.9.1/gems/sprockets-2.9.3/lib/sprockets/base.rb:287:in `find_asset'
/usr/lib/ruby/gems/1.9.1/gems/sprockets-2.9.3/lib/sprockets/index.rb:61:in `find_asset'
/usr/lib/ruby/gems/1.9.1/gems/jekyll-assets-0.5.1/lib/jekyll/assets_plugin/patches/index_patch.rb:19:in `find_asset_with_jekyll'
/usr/lib/ruby/gems/1.9.1/gems/sprockets-2.9.3/lib/sprockets/environment.rb:75:in `find_asset'
/usr/lib/ruby/gems/1.9.1/gems/jekyll-assets-0.5.1/lib/jekyll/assets_plugin/environment.rb:38:in `find_asset'
/usr/lib/ruby/gems/1.9.1/gems/sprockets-2.9.3/lib/sprockets/base.rb:295:in `[]'
/usr/lib/ruby/gems/1.9.1/gems/jekyll-assets-0.5.1/lib/jekyll/assets_plugin/patches/site_patch.rb:43:in `asset_path'
/usr/lib/ruby/gems/1.9.1/gems/jekyll-assets-0.5.1/lib/jekyll/assets_plugin/renderer.rb:21:in `render_asset_path'
/usr/lib/ruby/gems/1.9.1/gems/jekyll-assets-0.5.1/lib/jekyll/assets_plugin/renderer.rb:35:in `render_stylesheet'
/usr/lib/ruby/gems/1.9.1/gems/jekyll-assets-0.5.1/lib/jekyll/assets_plugin/tag.rb:14:in `render'
/usr/lib/ruby/gems/1.9.1/gems/liquid-2.5.0/lib/liquid/block.rb:106:in `block in render_all'
/usr/lib/ruby/gems/1.9.1/gems/liquid-2.5.0/lib/liquid/block.rb:93:in `each'
/usr/lib/ruby/gems/1.9.1/gems/liquid-2.5.0/lib/liquid/block.rb:93:in `render_all'
/usr/lib/ruby/gems/1.9.1/gems/liquid-2.5.0/lib/liquid/block.rb:82:in `render'
/usr/lib/ruby/gems/1.9.1/gems/liquid-2.5.0/lib/liquid/template.rb:124:in `render'
/usr/lib/ruby/gems/1.9.1/gems/liquid-2.5.0/lib/liquid/template.rb:132:in `render!'
/usr/lib/ruby/gems/1.9.1/gems/jekyll-1.0.2/lib/jekyll/convertible.rb:77:in `render_liquid'
/usr/lib/ruby/gems/1.9.1/gems/jekyll-1.0.2/lib/jekyll/convertible.rb:101:in `render_all_layouts'
/usr/lib/ruby/gems/1.9.1/gems/jekyll-1.0.2/lib/jekyll/convertible.rb:136:in `do_layout'
/usr/lib/ruby/gems/1.9.1/gems/jekyll-1.0.2/lib/jekyll/post.rb:285:in `render'
/usr/lib/ruby/gems/1.9.1/gems/jekyll-1.0.2/lib/jekyll/site.rb:230:in `block in render'
/usr/lib/ruby/gems/1.9.1/gems/jekyll-1.0.2/lib/jekyll/site.rb:229:in `each'
/usr/lib/ruby/gems/1.9.1/gems/jekyll-1.0.2/lib/jekyll/site.rb:229:in `render'
/usr/lib/ruby/gems/1.9.1/gems/jekyll-1.0.2/lib/jekyll/site.rb:44:in `process'
/usr/lib/ruby/gems/1.9.1/gems/jekyll-1.0.2/lib/jekyll/command.rb:18:in `process_site'
/usr/lib/ruby/gems/1.9.1/gems/jekyll-1.0.2/lib/jekyll/commands/build.rb:23:in `build'
/usr/lib/ruby/gems/1.9.1/gems/jekyll-1.0.2/lib/jekyll/commands/build.rb:7:in `process'
/usr/lib/ruby/gems/1.9.1/gems/jekyll-1.0.2/bin/jekyll:59:in `block (2 levels) in <top (required)>'
/usr/lib/ruby/gems/1.9.1/gems/commander-4.1.3/lib/commander/command.rb:180:in `call'
/usr/lib/ruby/gems/1.9.1/gems/commander-4.1.3/lib/commander/command.rb:180:in `call'
/usr/lib/ruby/gems/1.9.1/gems/commander-4.1.3/lib/commander/command.rb:155:in `run'
/usr/lib/ruby/gems/1.9.1/gems/commander-4.1.3/lib/commander/runner.rb:402:in `run_active_command'
/usr/lib/ruby/gems/1.9.1/gems/commander-4.1.3/lib/commander/runner.rb:66:in `run!'
/usr/lib/ruby/gems/1.9.1/gems/commander-4.1.3/lib/commander/delegates.rb:11:in `run!'
/usr/lib/ruby/gems/1.9.1/gems/commander-4.1.3/lib/commander/import.rb:10:in `block in <top (required)>'
Build Failed
```

My Gemfile.lock:

```
 $ cat Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    classifier (1.3.3)
      fast-stemmer (>= 1.0.0)
    colorator (0.1)
    commander (4.1.3)
      highline (~> 1.6.11)
    directory_watcher (1.4.1)
    execjs (1.4.0)
      multi_json (~> 1.0)
    fast-stemmer (1.0.2)
    highline (1.6.18)
    hike (1.2.2)
    jekyll (1.0.2)
      classifier (~> 1.3)
      colorator (~> 0.1)
      commander (~> 4.1.3)
      directory_watcher (~> 1.4.1)
      kramdown (~> 1.0.2)
      liquid (~> 2.3)
      maruku (~> 0.5)
      pygments.rb (~> 0.5.0)
      safe_yaml (~> 0.7.0)
    jekyll-assets (0.5.1)
      jekyll (~> 1.0)
      sprockets (~> 2.9)
    kramdown (1.0.2)
    liquid (2.5.0)
    maruku (0.6.1)
      syntax (>= 1.0.0)
    multi_json (1.7.3)
    posix-spawn (0.3.6)
    pygments.rb (0.5.0)
      posix-spawn (~> 0.3.6)
      yajl-ruby (~> 1.1.0)
    rack (1.5.2)
    rdiscount (2.0.7.3)
    safe_yaml (0.7.1)
    sass (3.2.9)
    sprockets (2.9.3)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    syntax (1.0.0)
    tilt (1.4.1)
    uglifier (2.1.0)
      execjs (>= 0.3.0)
      multi_json (~> 1.0, >= 1.0.2)
    yajl-ruby (1.1.0)

PLATFORMS
  ruby

DEPENDENCIES
  jekyll
  jekyll-assets
  rdiscount
  sass
  uglifier
```
