### ISSUE TITLE
SASS/SCSS asset_path not working correctly

### ISSUE THREAD

**Issue by hv15** [envygeeks/jekyll-assets#38]
Hi ixti,

I've created a mixin:

``` SCSS
@mixin font-face($nick, $name, $file, $weight: normal, $style: normal){
    @font-face {
        font-family: $nick;
        src: url(asset_path("#{$file}.eot"));
        src: url(asset_path("#{$file}.eot?#iefix")) format('embedded-opentype'),
             url(asset_path("#{$file}.woff")) format('woff'),
             url(asset_path("#{$file}.ttf")) format('truetype'),
             url(asset_path("#{$file}.svg##{$name}")) format('svg');
        font-weight: $weight;
        font-style: $style;
    }
}
```

However, when I build the site I get the following error:

```
 Liquid Exception: Couldn't find file 'font/lacuna-webfont.eot?#iefix' (in /cygdrive/c/Users/Hans/git/hans.viessmann.co/_assets/stylesheets/main.css.scss) in default.html
```

I just recently updated to 0.6.0, have there been any changes in how asset_path works?

Thanks
