### ISSUE TITLE
jekyll-assets ignores the _config.yml

### ISSUE THREAD

**Issue by sebald** [envygeeks/jekyll-assets#47]
Hi,

first of all this also could be just an issue because I am not very familiar with Ruby, but when I build my site the settings for thr `jekyll-assets`plugin get completely ignored.

The liquid tags work and files reference by the tags get copied to the build directory. But my settings (see below) are ignored:

```
permalink: /:categories/:title.html
exclude: [scss, Gemfile, Gemfile.lock]
include: [.htaccess]
safe: false
assets:
  cache: false
  sources:
    - _assets/inmg
    - _assets/js
    - _assets/css
    - _assets/fonts
```

I am very confused and have no clue what I am doing wrong, because the plugin works just all settings are getting ignored :(

EDIT: Also, `{{ site.assets }}` works and displays all settings.

BTW I am building the site on my Windows machine.
