### ISSUE TITLE
Request for an image optimization example in the docs

### ISSUE THREAD

**Issue by aaronwolen** [envygeeks/jekyll-assets#508]
- [x] I tried updating to the latest version.
  - [ ] I can't, there is an issue.
- [ ] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
- [ ] I Am on Linux
- [x] I Am on macOS

## Description

I'm having trouble getting image optimization to work with v3.0.7. This is likely an error on my part but the docs are a little light on details, which makes troubleshooting difficult.  A usage example would be a big help and much appreciated. 

Here's what I've tried so far: I started with a fresh site created with jekyll 3.7.3, added jekyll-assets and image_optim to the `Gemfile`, and modified `_config.yaml` with the following:

```yaml
plugins:
  - jekyll-assets

assets:
  compression: false
  plugins:
    img:
      optim:
        default:
          verbose: true
        zero_png:
          advpng:
            level: 0
          optipng:
            level: 0
          pngout:
            strategy: 4
```

Also added a large, unoptimized image file to `_assets/images/example.png`.

My understanding from the docs is the following should invoke the `zero_png` preset specified in `_config.yaml`:

```
{% asset example.png @image_optim:zero_png %}
```

However, the image is simply copied over without being optimized. Am I missing something?

**Comment by envygeeks** [comment]
I wish I could provide more documentation, but I don't use the plugin as every one of my images is already optimized before it even enters the repository... this plugin was provided as a contribution. Maybe @alexey-pelykh (IIRR he's the one who contributed it,) can provide more information.  I do know that in 3.x we straight up ship the options into image optim so whatever their documentation states is what you should give us.

I can say this from the outset, they might need extra stuff, and they might fail silently like we do with plugins, where if it doesn't exist it doesn't get ran.  And to also add, anything that states 0 probably disables compression.  Have you checked their documentation to make sure you have everything they require?

**Comment by aaronwolen** [comment]
Thanks! I did read through the [image_optim](https://github.com/toy/image_optim_rails) docs and am able to use it successfully via the cli. Good point regarding the 0s. They were originally configured differently (i.e., > 0) but in the service of creating a MWE I mirrored what's in the docs. 

Hopefully @alexey-pelykh  can shine some light on this issue because image optimization would be a very welcome addition to an already excellent gem.

**Comment by aaronwolen** [comment]
Awesome! Thanks for doing this. Are these changes slated for v3.0.9?

**Comment by envygeeks** [comment]
Undetermined right now.  It could be v3.0.9 or it could be v3.1.0, depending on if I keep going with bug fixes or add in a few features along the way.

**Comment by migueldemoura** [comment]
@aaronwolen did you manage to get this working? I just tried this and didn't have any luck:

``` yml
  plugins:
    img:
      optim:
        preset:
          advpng:
            level: 4
          jpegoptim:
          gifsicle:
          advpng: false
          pngcrush: false
          pngout: false
          pngquant: false
          optipng: false
          jhead: false
          jpegrecompress: false
          jpegtran: false
          svgo: false
```

``` liquid
{% asset '{{ include.path }}' optim='preset' %}
```

Image is still copied over.

**Comment by lucasnantonio** [comment]
I also don't understand how to get this working :( my images all get to the assets folder with the original size

**Comment by shalzz** [comment]
Hello, image_optim does somehow work for me but the image is saved with a different name as well as the {% asset b.png @optim %} not actually inserting an img tag

**Comment by shalzz** [comment]
Ok so I does work with @path where it gives me the correct path of the optimised image.
But I would expect  it to also insert the img tag instead of me wrapping it in one.

**Comment by migueldemoura** [comment]
@shalzz, can you share a repo with a working example? I can't get this to work.

**Comment by migueldemoura** [comment]
@shalzz, can you share a repo with a working example? I can't get this to work. Thanks!

**Comment by shalzz** [comment]
@migueldemoura I am experiencing this on my blog:
https://github.com/shalzz/shalzz.github.io/blob/travis/_includes/asset.html#L5
Just having @optim doesn't work

**Comment by JaimeObregon** [comment]
I have stumbled upon the same issue. There is clearly something I am doing wrong, but the documentation does not provide a clue in the form of a working example.

This is my `Gemfile` (simplified) and I have both `image_optim` and `image_optim_pack` installed:

```ruby
group :jekyll_plugins do
  gem 'jekyll-assets'
  gem "image_optim"
  gem "image_optim_pack"
end
```

In my `_config.yml` I have defined **two presets**: `default` and `optimized`:

```yml
assets:
  plugins:
    img:
      optim:
        default:
          verbose: false
        optimized:
          verbose: true
          optipng:
            level: 7
``` 

The relevant lines of my markup look like this:
```html
<picture>
  <source media="(max-width: 768px)" srcset="{% asset 'image.png' magick:resize=768x> magick:quality=95 optim=default @path %}">
  <source media="(max-width: 768px)" srcset="{% asset 'image.png' magick:resize=768x> magick:quality=95 optim=optimized @path %}">
```

And the output is being correctly built:
```html
<picture>
  <source media="(max-width: 768px)" srcset="/assets/f4d388-ca0628b323bf253db8a6dc87065939d2c9f1a0e46801198e87874ed28cf2302e.png">
  <source media="(max-width: 768px)" srcset="/assets/5e001e-9f58b168a41c4bd8f927879e8cbfcd91e4491d025d0d0513026ae0ee1ad1d161.png">
```

However, **both generated images are the same size**.

I am inclined to think this is happening because both are being generated with the `default` preset, because **during the build I never get a verbose output despite I have set `verbose: true` under the `optimized` preset**. However I do get see the verbose output when I enable it under `default`.
