### ISSUE TITLE
Compile assets paths from YAML Front Matter

### ISSUE THREAD

**Issue by renshuki** [envygeeks/jekyll-assets#520]
Hi @envygeeks,

I have some SEO variables (that I use for `jekyll-seo-tag` plugin) set in the YAML Front Matter for each post like that:

```yaml
---
title:  "Example title"
category: Example
image: /assets/feature-image.jpg
description: "Example description"
---
```

> The SEO tag will respect the following YAML Front Matter if included in a post, page, or document:
> 
> title - The title of the post, page, or document
> description - A short description of the page's content
> image - URL to an image associated with the post, page, or document (e.g., /assets/page-pic.jpg)
> author - Page-, post-, or document-specific author information (see Advanced usage)
> lang - Page-, post-, or document-specific language information

Unfortunately it seems `asset` tag can't be used in Front Matter so images defined there are not compiled. Of course, one solution would be to add them manually in `raw_precompile` option but it's not really convenient imo.  Maybe I'm missing something but do you have any solution for that or do you think it should be implemented?

Thank you for your awesome work on this plugin 😄 
Keep up the good work.
