### ISSUE TITLE
Jekyll-Assets 3 doubles build time

### ISSUE THREAD

**Issue by abeMedia** [envygeeks/jekyll-assets#541]
I was using jekyll-assets 2 up until recently but thought I better upgrade since v3 has been out for quite some time. Also the use of sprockets v4 promised performance gains... 
Sadly that was not the case! My build time used to be around 200 seconds (when images are already cached) and now the build time has increased to over 400 seconds (also with images cached)!

I have the feeling the images are being rebuilt on each build as this shouldn't be that slow...

FYI I'm using `JEKYLL_ENV=production` and the following config:
```yaml
assets:
  plugins:
    img:
      optim:
        default:
          pack: true
          optipng:
            level: 7
          pngquant:
            speed: 1
```
