### ISSUE TITLE
How to get autoprefixer to work

### ISSUE THREAD

**Issue by kslstn** [envygeeks/jekyll-assets#549]
- [x] I tried updating to the latest version.
- [x ] I Am on macOS

## Description

I can't get jekyll-assets and autoprefixer to work. Autoprefixer is not the only reason I'd like to use jekyll-assets, but for now it would suffice to just enable that plugin.

## Steps

This is my `Gemfile`:
```
gem "jekyll-assets"
gem "autoprefixer-rails"
gem "uglifier"

gem 'jekyll'

group :jekyll_plugins do
  gem "jekyll-sitemap"
  gem "jekyll-paginate"
  gem 'jekyll-feed'
  gem 'jekyll-extlinks'
end
```

After some manual installs, bundle install says, among other things 'Using jekyll-assets 3.0.11' and 'Bundle complete'.

I also created `/_plugins/ext.rb` and added:

```
require "jekyll-assets"
require "sprockets"
```

I modified _config.yml to contain among other things:
```

# Build Settings
environment: prod
sass:
    sass_dir: ./_scss
    style: compressed
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-extlinks
  - jekyll-assets
paginate: 8
paginate_path: "/page/:num"

include: ['_pages', '.htacces']
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "_config.yml", ".gitignore", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "publish.sh"]

#jekyll-assets
assets:
  compress:
    css:  sass
    js:   uglifier
  autoprefixer:
    browsers: ["last 5 versions","> 5%","IE 9"]
  plugins:
    css: { autoprefixer: {}}
```

Then I tried `bundle exec jekyll build` and `JEKYLL_ENV=production bundle exec jekyll build`

## Output
The _site/assets/css/style.css does not contain prefixed CSS.

## Expected
I was hoping to get browser prefixes for CSS properties such as box-shadow and text-decoration-color.

I'm sorry if this is a problem of me not know how to handle gems well. I have no experience with Ruby and was under the impression one could use Jekyll's ecosystem without actually having to understand what happens in the plugins.

**Comment by envygeeks** [comment]
3.0 is no longer supported, please update and then report your status after that, thanks!

**Comment by kslstn** [comment]
Alright, thanks for pointing that out. Can you perhaps explain how I install the latest update? I installed 3.0.11 using the instructions I found in the readme. When I do `bundle update`, it says 'jekyll-assets 3.0.11' and 'Bundle updated'. 

I also tried:
```
gem update jekyll-assets
Updating installed gems
Nothing to update
```
And:

```
gem install jekyll-assets 3.1.0
Successfully installed jekyll-assets-3.0.11
Parsing documentation for jekyll-assets-3.0.11
Done installing documentation for jekyll-assets after 0 seconds
ERROR:  Could not find a valid gem '3.1.0' (>= 0) in any repository
1 gem installed

```

**Comment by migueldemoura** [comment]
@kslstn 

> gem install jekyll-assets 3.1.0

should be:

> gem install jekyll-assets 3.0.11

**Comment by kslstn** [comment]
I believe what's going wrong is that I don't know how to interpret the installation instructions, or that something is missing there. All I found in the readme is:

> Installing
> gem "jekyll-assets", group: :jekyll_plugins
> gem "jekyll-assets", git: "https://github.com/envygeeks/jekyll-assets", group: :jekyll_plugins
> gem "jekyll-assets", "~> x.x.alpha", group: :jekyll_plugins

But where am I to do that? Not in the terminal, I found. Instead I did the steps I listed in my opening post.

**Comment by jalcine** [comment]
@kslstn You add this to your "Gemfile".

**Comment by migueldemoura** [comment]
Your Gemfile should have something like this:

https://github.com/migueldemoura/migueldemoura.com/blob/master/Gemfile
```
group :jekyll_plugins do
    gem 'jekyll-assets', '>= 3.0.11'
end
```

**Comment by kslstn** [comment]
Thanks for the details, Miguel! I tried it, now things are installed without errors, including jekyll-assets. However, when I do `exec bundle jekyll build`, CSS is still not prefixed. I tried with and without this in my _config.yml:

> #jekyll-assets
> assets:
>   compress:
>     css:  sass
>     js:   uglifier
>   autoprefixer:
>     browsers: ["last 5 versions","> 1%","IE 6"]
>   plugins:
>     css: { autoprefixer: {}}

On a blog I read I should move the CSS from /assets to /_assets, but that doesn't seem to make a difference other than getting the CSS getting ignored altogether by Jekyll.

**Comment by migueldemoura** [comment]
Please add `gem 'autoprefixer-rails', '>= 9.1.0'` to your Gemfile as well.
It should look something like this:

``` ruby
gem 'autoprefixer-rails', '>= 9.1.0

group :jekyll_plugins do
    gem 'jekyll-assets', '>= 3.0.11'
end
```

**Comment by envygeeks** [comment]
That's still not gonna help

> other than getting the CSS getting ignored altogether by Jekyll

You need to read the documentation here https://github.com/envygeeks/jekyll-assets#tag--asset--img Jekyll-Assets doesn't magically compile your assets, you need to explicitly reference them with the `{% asset %}` tag, or they will be ignored, in the same way that Rails, or other asset management utilities should.

**Comment by kslstn** [comment]
Thanks for pointing that out! I did actually look at the documentation. I didn't know the images part applied to CSS too. Only familiar with Webpack as an asset pipeline, I apparently expected magic. Anyway, full of shame, but also hope, I tried:

```
	{% asset src /css/style.scss @path %}
	<link rel="stylesheet" href="src">
```
and variations thereof. But alas:

```
Regenerating: 1 file(s) changed at 2018-08-16 20:59:33
                    _includes/head.html
  Liquid Exception: Liquid syntax error (/Users/.../_includes/head.html line 109): Unknown tag 'asset' included in /_layouts/base.html
             Error: Liquid syntax error (/Users/.../_includes/head.html line 109): Unknown tag 'asset' included 
             Error: Run jekyll build --trace for more information.
```

**Comment by envygeeks** [comment]
Hey @kslstn

Make sure Jekyll-Assets is in "jekyll_plugins" as @migueldemoura said. Your tag usage isn't how Jekyll-Assets works either, it's: `{% asset style.css %}` and `style.scss` needs to be in `_assets/css/style.scss`, if you reference assets by "scss" we will give you the raw source, you need to reference them by their final content typed extension, and you don't need that link, we deal with that for you, and if you need to add attributes you can do that too.

**Comment by kslstn** [comment]
Thanks @envygeeks! When I understand it correctly, this is the installation and configuration process:

**Add to Gemfile:**
```
gem "autoprefixer-rails"
gem "uglifier"

group :jekyll_plugins do
  gem 'jekyll-assets', '>= 3.0.11'
end
```

**Add something like this to \_config.yml:**
```
assets:
  compress:
    css:  sass
    js:   uglifier
  autoprefixer:
    browsers: ["last 5 versions","> 5%","IE 9"]
  plugins:
    css: { autoprefixer: {}}
```

**Create _/assets/style.scss**

**In liquid template:**
Replace:
`<link rel="stylesheet" href="{{ "/assets/css/style.css" | prepend: site.baseurl }}">`
with:
`{% asset style.css %}`

**Run in Terminal:**
`bundle install`
`bundle exec jekyll build`

----------------------

It still doesn't work for me though... Bundle says:
_Liquid Exception: couldn't find file 'style.css' in_ and then a whole lot of directories and then _jekyll 3.8.3 | Error:  couldn't find file 'style.css' in `_posts/blog/2013-09-10-title.md'_
