### ISSUE TITLE
Integrity config option ignored

### ISSUE THREAD

**Issue by chalin** [envygeeks/jekyll-assets#556]
- [x] I tried updating to the latest version. I'm using:
  - jekyll (3.8.3)
  - jekyll-assets (3.0.11)
  - sprockets (4.0.0.beta8)
  - ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-darwin17]
- [x] I Am on macOS

## Description

When building a Jekyll site in development mode, regardless of the `integrity` setting, I'm always getting the SRI hash added to the asset path, for example:

```html
<link rel="stylesheet" type="text/css" href="/assets/main-9a79ad00d1edd0cc4b69b07c01a8a8587d6537a0fb669e60e2187a79d54d0d2a.css">
```

Even if my config.yml contains

```yaml
assets:
  defaults:
    js: { integrity: false }
    css: { integrity: false }
    img: { integrity: false }
```

And even if I use `!integrity`, for example:

```
{% asset main.css !integrity %}
```

## Expected

I expect the SRI hash to be includes in asset paths when in production mode only, not development mode.

Any clues as to what might be going on? If not, I'll try to produce a small repro.

cc @kwalrath @filiph
