### ISSUE TITLE
CSS Font Family src with ? Throws Exception

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [envygeeks/jekyll-assets#580]
- [ ] I tried updating to the latest version
  - [ ] I can't, there is an issue
  - [ ] This is about an < latest
    - [ ] I understand older versions may be unsupported
- [ ] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
  - [ ] Other  Bash on Windows
- [x] I Am on Linux
  - [ ] Ubuntu
  - [ ] Fedora
  - [ ] CentOS
  - [ ] Redhat
  - [x] Debian
- [ ] I am on macOS 10.13
- [ ] I am on macOS 10.14
- [ ] I'm on Docker
  - [ ] I understand Docker may be unsupported

## Description

I have a font-family that uses ?s in its src URLs. Apparently this results in a liquid exception being thrown because of jekyll-assets or liquid-tag-parser.
## Steps

This is the code that I am using:
```css
@font-face {
    font-family: 'fontello';
    src: url(asset_path("'fontello/fontello.eot?89493118'"));
    src: url(asset_path("'fontello/fontello.eot?89493118#iefix'")) format("embedded-opentype"), asset_url("'fontello/fontello.woff2?89493118'") format("woff2"), asset_url("'fontello/fontello.woff?89493118'") format("woff"), asset_url("'fontello/fontello.ttf?89493118'") format("truetype"), asset_url("'fontello/fontello.svg?89493118#fontello'") format("svg");
    font-weight: normal;
    font-style: normal;
}
```

## Output
Whenever I build it using the latest of everything I get this Liquid Exception. 
```sh
Liquid Exception: Liquid error (line 7): Unmatched double quote: "'fontello/fontello.woff2 \\@path" in /_layouts/default.html
bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)
Liquid::ArgumentError: Liquid error (line 7): Unmatched double quote: "'fontello/fontello.woff2  \\@path"
```

## Expected 
I am expecting it to retrieve the fonts correctly with the question marks.
