### ISSUE TITLE
CSS Font Face src file name parsed as property and invalid css

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [envygeeks/jekyll-assets#581]
- [ ] I tried updating to the latest version
  - [ ] I can't, there is an issue
  - [ ] This is about an < latest
    - [ ] I understand older versions may be unsupported
- [ ] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
  - [ ] Other  Bash on Windows
- [x] I Am on Linux
  - [ ] Ubuntu
  - [ ] Fedora
  - [ ] CentOS
  - [ ] Redhat
  - [x] Debian
- [ ] I am on macOS 10.13
- [ ] I am on macOS 10.14
- [ ] I'm on Docker
  - [ ] I understand Docker may be unsupported

## Description
I have a font-family with multiple sources. For some reason this results in a liquid exception being thrown despite it being valid css. It seems to be treating the font file name as a CSS property, and thus expects a value instead of the file extension. 

## Steps

This is the code that I am using:

```css
@font-face {
    font-family: "Moon Flower";
    font-style: normal;
    font-weight: 400;
    src: asset_url("'Moon Flower/Moon_Flower.eot'");
    /*src: asset_url("'Moon Flower/Moon_Flower.eot?#iefix'") format("embedded-opentype"), */
    src: asset_url("'Moon Flower/Moon_Flower.ttf'") format("truetype"), asset_url("'Moon Flower/Moon_Flower.woff'") format("woff"), asset_url("'Moon Flower/Moon_Flower.svg'") format("svg");
    unicode-range: U+?????;
}
```

## Output
Whenever I build it using the latest of everything I get this Liquid Exception. I temporarily commented out one line with a ? in the src url due to the issue I opened earlier.
```sh
Liquid Exception: Error: Invalid CSS after "...7938c1310d08558": expected expression (e.g. 1px, bold), was ".eot);" on line 5 of _assets/css/fonts.scss >> 68b855e8b7b24c91dd8aadb5e1c7938c1310d08558.eot); ------------------------------------------^ in /_layouts/default.html
bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)
SassC::SyntaxError: Error: Invalid CSS after "...7938c1310d08558": expected expression (e.g. 1px, bold), was ".eot);"
        on line 5 of _assets/css/fonts.scss
>> 68b855e8b7b24c91dd8aadb5e1c7938c1310d08558.eot);

   ------------------------------------------^
```

## Expected

I expect it to replace asset_url with url with the file name without any errors.
