### ISSUE TITLE
Source maps don't generate

### ISSUE THREAD

**Issue by Nowaker** [envygeeks/jekyll-assets#614]
- [x] I tried updating to the latest version
- [x] I Am on Linux
  - [x] Other: Arch Linux
- [x] I am on macOS 10.14
- [x] I'm on Docker
  - [x] I understand Docker may be unsupported

## Steps

Neither of these configs generate source maps for either SCSS:

```
assets:
  source_maps: true
  compression: false
  prefix: '/assets'
  sources:
  - assets
  - assets/js
```

```
assets:
  source_maps: true
  compression: true
  prefix: '/assets'
  sources:
  - assets
  - assets/js
```

Adding `JEKYLL_ENV=production` or `JEKYLL_ENV=development` on top of the config above still doesn't trigger the generation of source maps.

## Output

```
[2019-08-22 18:21:37] ERROR `/assets/css/site-f35f10fd08b6aa61d32980178990453f2e8f8f1dc43e5fe411ad14a31bf44821.css.map' not found.
[2019-08-22 18:20:41] ERROR `/assets/js/site-b534dbc9c94ee86fec4925290f78053cfc0affe8f0d2c461bace7428df0c4983.js.map' not found.
```

URLs without a `.map` work correctly and display a compressed JS/CSS.

## Expected

Source maps should be generated.
