### ISSUE TITLE
CDN destination is treated as boolean 

### ISSUE THREAD

**Issue by mwt** [envygeeks/jekyll-assets#657]
- [X] I tried updating to the latest version
  - [ ] I can't, there is an issue
  - [ ] This is about an < latest
    - [ ] I understand older versions may be unsupported
- [ ] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
  - [ ] Other  Bash on Windows
- [X] I Am on Linux
  - [X] Ubuntu
  - [ ] Fedora
  - [ ] CentOS
  - [ ] Redhat
  - [ ] Debian
- [ ] I am on macOS 10.13
- [ ] I am on macOS 10.14
- [ ] I'm on Docker
  - [ ] I understand Docker may be unsupported

## Description

I am having an issue similar to #567. The assets:cdn:destination is currently being used as a boolean. If true, it applies assets:destination to the CDN URL. This blocks the usage of CDNs with subdirectories and contradicts the documentation.
```
assets:
  compression: true
  defaults:
    js: { integrity: false }
    css: { integrity: false }
    img: { integrity: false }
  cdn:
    baseurl: false
    destination: "/v7"
    url: "https://ajsxgydazo.cloudimg.io"
```
I have tried the following two commands
```
JEKYLL_ENV=production bundle exec jekyll build
```
and 
```
bundle exec jekyll build
```
I drafted a fix in [my fork](https://github.com/ThinkTutor/jekyll-assets) that I am using in production. I don't actually know ruby though. In fact, this is my first time looking at the language. So, it's probably junk.

## Steps

- Try to use the CDN destination feature in the config.

## Output

```
<link rel="stylesheet" type="text/css" href="https://ajsxgydazo.cloudimg.io/assets/main-4ecf126146f6368f46cfd8662ce8d6d5be9ad0976851eea92e4cb69161a1f6d5e115a469e29a2d56716a05ec266a06e45ec58f50f5dde89611b34df744964544.css">
```

## Expected

```
<link rel="stylesheet" type="text/css" href="https://ajsxgydazo.cloudimg.io/v7/assets/main-4ecf126146f6368f46cfd8662ce8d6d5be9ad0976851eea92e4cb69161a1f6d5e115a469e29a2d56716a05ec266a06e45ec58f50f5dde89611b34df744964544.css">
```
