### ISSUE TITLE
asset_url helper not working in included .scss file

### ISSUE THREAD

**Issue by sentience** [envygeeks/jekyll-assets#83]
In _assets/stylesheets/application.css.scss:

``` scss
$color-personal-accent: #D98611;
@import "objects/hero";
```

In _assets/stylesheets/objects/_hero.scss:

``` scss
.hero {
  background: $color-personal-accent url(asset_path('bg-personal.png')) center bottom no-repeat;
}
```

Output:

``` css
.hero {
  background: #d98611 url(asset_path("bg-personal.png")) center bottom no-repeat;
}
```

Why didn’t the `asset_path` helper work in this case?
