### ISSUE TITLE
Assets source lookup order

### ISSUE THREAD

**Issue by silvenon** [envygeeks/jekyll-assets#88]
When I specify my sources like this:

``` yml
assets:
  js_compressor: uglifier
  css_compressor: sass
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
    - bower_components
    - bower_components/bootstrap-sass-official/assets/javascripts
    - bower_components/bootstrap-sass-official/assets/stylesheets
```

does it become the order of the lookup? I did `@import "bootstrap"`, which would import `bower_components/bootstrap-sass-official/assets/stylesheets`, but when I create `_assets/stylesheets/_bootstrap.scss` I would like it to read that one, which is not the case.

How does the lookup work?
